Added optional endowments param to executeSnap
MetaMask/iframe-execution-environment pull request #39
Opened 2021-12-13 22:55 UTC by shanejonas

This adds an optional `endowments` parameter to `executeSnap` to allow access to globals like `fetch` per snap.

##### Example with `fetch` endowment
![image](https://user-images.githubusercontent.com/364566/145901378-b23a4e48-1e91-4f61-aed7-3a6d8be8c817.png)

![image](https://user-images.githubusercontent.com/364566/145901420-07e6808c-1c34-475f-8046-843aaca7b27d.png)

##### Example with no endowments:
![image](https://user-images.githubusercontent.com/364566/145901929-8443a81b-637b-406c-921d-e7ac2419c183.png)

2021-12-13 23:07 UTC, shanejonas commented on openrpc.json
> +          "description": "a list off endowments to provide to SES",
```suggestion
          "description": "a list of endowments to provide to SES",
```

2021-12-13 23:08 UTC, shanejonas commented on src/controller.ts
> +
```suggestion
```

2021-12-13 23:08 UTC, shanejonas commented on src/controller.ts
> +      // fetch: window.fetch.bind(window),
```suggestion
```

2021-12-13 23:08 UTC, shanejonas commented on src/controller.ts
>        XMLHttpRequest,
```suggestion
```

2021-12-13 23:42 UTC, rekmarks requested changes

2021-12-13 23:42 UTC, rekmarks commented on openrpc.json
> +          "description": "a list of endowments to provide to SES",
```suggestion
          "description": "A list of endowments to provide to SES",
```

2021-12-13 23:42 UTC, rekmarks commented on src/controller.ts
> +      });
Some defensive improvements:
```suggestion
    if (_endowments && _endowments.length > 0) {
      _endowments.forEach((_endowment) => {
        if (!(_endowment in window)) {
          throw new Error(`Unknown endowment: "${_endowment}".`);
        }

        
        endowments[_endowment] = typeof globalValue === 'function'
          ? globalValue.bind(window)
          : globalValue;
      });
```

2021-12-13 23:42 UTC, rekmarks commented on src/controller.ts
>        setTimeout,
Note for follow-up: `setTimeout` is a sandbox escape. We have to fix it.

2021-12-13 23:43 UTC, rekmarks commented on src/controller.ts
>        XMLHttpRequest,
`WebSocket` also needs to go, unless we decide to include it.

2021-12-13 23:54 UTC, shanejonas commented on src/controller.ts
> +  StringDoaGddGA,
```suggestion
```

2021-12-14 01:01 UTC, rekmarks approved these changes
LGTM!

2021-12-14 01:16 UTC, merged