Added lockdown-more + update ses to ^0.15.3
MetaMask/iframe-execution-environment pull request #42
Opened 2021-12-15 00:58 UTC by shanejonas

2021-12-15 01:06 UTC, shanejonas commented on src/lockdown-more.ts
> +          harden((globalThis as any)[propertyName.toString()]);
added both `toString()` here as it can only take a string

2021-12-15 03:19 UTC, rekmarks requested changes

2021-12-15 03:19 UTC, rekmarks commented on src/lockdown.ts
> +  console.log('locked down.');
I don't think we need this.
```suggestion
```

2021-12-15 03:19 UTC, rekmarks commented on src/lockdown.ts
> +  throw error;
Are we confident that this will prevent further script execution?

2021-12-15 03:19 UTC, rekmarks commented on src/lockdown-more.ts
> +          harden((globalThis as any)[propertyName.toString()]);
Hm, `namedIntrinsics` and `globalProperties` should only contain strings, so we should cast them appropriately instead I think.

2021-12-15 03:19 UTC, rekmarks commented on src/index.ts
> +import './lockdown-more'; //eslint-disable-line
Hm, I'm not sure if this is good enough, or if we need to prepend `ses/dist/lockdown.umd.min.js` to the bundle after `tsc` and `webpack`.

@kumavis, if this file is the first thing that executes, are we locked down? I suppose it could depend on what our build process does.

2021-12-15 03:31 UTC, kumavis commented on src/index.ts
> +import './lockdown-more'; //eslint-disable-line
you dont want to transform ses shim at all

2021-12-16 03:10 UTC, shanejonas commented on src/controller.ts
> +declare class Compartment {
I dont want to import `ses` again in this file just to get the types.

2021-12-16 03:11 UTC, shanejonas commented on src/controller.ts
> +      const compartment = new Compartment({ //eslint-disable-line
```suggestion
      const compartment = new Compartment({
```

2021-12-16 03:11 UTC, shanejonas commented on tsconfig.json
> +  "include": ["./src/**/*.ts", "./openrpc.json", "src/lockdown-more.js", "src/lockdown/lockdown.js", "src/lockdown/lockdown-more.js"]
```suggestion
  "include": ["./src/**/*.ts", "./openrpc.json", "src/lockdown/lockdown.js", "src/lockdown/lockdown-more.js"]
```

2021-12-16 03:19 UTC, shanejonas commented on tsconfig.json
> +    "src/lockdown-more.js",
```suggestion
```

2021-12-16 04:47 UTC, rekmarks approved these changes

2021-12-16 04:49 UTC, merged